
runtime: php
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

runtime_config:
  document_root: web
env_variables:
  MYSQL_DSN: mysql:dbname=peritaje;unix_socket=/cloudsql/peritaje-204822:southamerica-east1:peritaje
  MYSQL_USER: peritaje
  MYSQL_PASSWORD: jhonjtoloza
beta_settings:
      cloud_sql_instances: "peritaje-204822:southamerica-east1:peritaje"
skip_files:
- .env
- .idea/
- .git/
- web/assets/
- vendor/
- mail/
- commands/
- vagrant/